import React, { useEffect, useMemo, useState } from "react";
import { Download, Eye, EyeOff, FileLock2, Pencil, Plus, Save, Search, Trash2, X } from "lucide-react";
import api from "../../services/api";
import "./AdminDocuments.css";

const TYPES = ["10th / Matric", "12th / Intermediate", "B.Ed.", "BS", "Master", "MPhil", "PhD", "Postdoc", "CNIC", "Passport", "Other"];
const empty = { title:"", documentType:"10th / Matric", category:"Academic", description:"", holderName:"", institution:"", issueDate:"", documentNumber:"", visible:false, featured:false, order:0 };

export default function AdminDocuments(){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[file,setFile]=useState(null),[open,setOpen]=useState(false),[search,setSearch]=useState(""),[type,setType]=useState("All"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);const r=await api.get("/documents");setItems(r.data?.data||[])}catch(e){setError(e.response?.data?.message||"Unable to load documents.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>(type==="All"||x.documentType===type)&&JSON.stringify(x).toLowerCase().includes(search.toLowerCase())),[items,type,search]);
 const add=()=>{setEditing(null);setForm(empty);setFile(null);setError("");setOpen(true)};
 const edit=x=>{setEditing(x._id);setFile(null);setForm({...empty,...x,issueDate:x.issueDate?new Date(x.issueDate).toISOString().slice(0,10):""});setError("");setOpen(true)};
 const save=async e=>{e.preventDefault();if(!form.title.trim())return setError("Title is required.");try{setSaving(true);const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v??""));if(file)fd.append("file",file);const config={headers:{"Content-Type":"multipart/form-data"}};if(editing)await api.put(`/documents/${editing}`,fd,config);else await api.post("/documents",fd,config);setOpen(false);await load()}catch(e){setError(e.response?.data?.message||"Could not save document.")}finally{setSaving(false)}};
 const remove=async id=>{if(!window.confirm("Delete this document permanently?"))return;try{await api.delete(`/documents/${id}`);await load()}catch(e){setError(e.response?.data?.message||"Could not delete document.")}};
 const toggle=async id=>{try{await api.patch(`/documents/${id}/toggle`);await load()}catch(e){setError(e.response?.data?.message||"Could not change visibility.")}};
 const download=async x=>{try{const r=await api.get(`/documents/${x._id}/download`,{responseType:"blob"});const url=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=url;a.download=x.fileName||"document.pdf";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){setError(e.response?.data?.message||"Could not download document.")}};
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <div className="dv-page"><header className="dv-header"><div><span><FileLock2 size={14}/> PRIVATE DOCUMENT VAULT</span><h1>Documents</h1><p>Admin-only PDF storage. Documents are never exposed through the public portfolio API.</p></div><button className="dv-primary" onClick={add}><Plus size={17}/> Add Document</button></header>{error&&<div className="dv-error">{error}</div>}<div className="dv-toolbar"><div className="dv-search"><Search size={16}/><input placeholder="Search documents..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={type} onChange={e=>setType(e.target.value)}><option>All</option>{TYPES.map(t=><option key={t}>{t}</option>)}</select><small>{filtered.length} document(s)</small></div>{loading?<div className="dv-empty">Loading...</div>:filtered.length===0?<div className="dv-empty">No documents found.</div>:<div className="dv-list">{filtered.map(x=><article className="dv-card" key={x._id}><div><h3>{x.title}</h3><div className="dv-meta"><b>{x.documentType}</b><span>{x.category}</span>{x.institution&&<span>{x.institution}</span>}</div><p>{x.description||"No description provided."}</p><div className="dv-status"><span className={x.visible?"on":"off"}>{x.visible?<Eye size={13}/>:<EyeOff size={13}/>} {x.visible?"Visible":"Hidden"}</span><span>{x.fileName||"No PDF attached"}</span></div></div><div className="dv-actions"><button title="Download" disabled={!x.fileName} onClick={()=>download(x)}><Download size={17}/></button><button title={x.visible?"Hide":"Show"} onClick={()=>toggle(x._id)}>{x.visible?<EyeOff size={17}/>:<Eye size={17}/>}</button><button title="Edit" onClick={()=>edit(x)}><Pencil size={17}/></button><button className="danger" title="Delete" onClick={()=>remove(x._id)}><Trash2 size={17}/></button></div></article>)}</div>}
 {open&&<div className="dv-overlay"><form className="dv-modal" onSubmit={save}><div className="dv-modal-head"><div><span>{editing?"EDIT DOCUMENT":"NEW DOCUMENT"}</span><h2>{editing?"Edit Document":"Add Document"}</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="dv-form"><label><span>Title *</span><input value={form.title} onChange={e=>set("title",e.target.value)} required/></label><label><span>Document Type *</span><select value={form.documentType} onChange={e=>set("documentType",e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label><span>Category</span><input value={form.category} onChange={e=>set("category",e.target.value)}/></label><label><span>Holder Name</span><input value={form.holderName} onChange={e=>set("holderName",e.target.value)}/></label><label><span>Institution</span><input value={form.institution} onChange={e=>set("institution",e.target.value)}/></label><label><span>Issue Date</span><input type="date" value={form.issueDate||""} onChange={e=>set("issueDate",e.target.value)}/></label><label><span>Document Number</span><input value={form.documentNumber} onChange={e=>set("documentNumber",e.target.value)}/></label><label><span>Display Order</span><input type="number" value={form.order??0} onChange={e=>set("order",Number(e.target.value))}/></label><label className="full"><span>Description</span><textarea rows="4" value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className="full"><span>PDF File {editing?"(optional replacement)":""}</span><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>PDF only, maximum 15 MB.</small></label><label className="check"><input type="checkbox" checked={!!form.visible} onChange={e=>set("visible",e.target.checked)}/><span>Visible to admin/public status</span></label><label className="check"><input type="checkbox" checked={!!form.featured} onChange={e=>set("featured",e.target.checked)}/><span>Featured</span></label></div><div className="dv-modal-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="dv-primary" disabled={saving}><Save size={16}/>{saving?"Saving...":"Save Document"}</button></div></form></div>}
 </div>
}
