import React,{useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {ArrowLeft,ArrowUpRight} from "lucide-react";
import api from "../../services/api";
import "./PublicPortfolio.css";
const cfg={education:"Education",experience:"Experience",publications:"Publications",projects:"Projects","research-resources":"Research Resources","project-wins":"Project Wins",supervision:"Supervision",certificates:"Certifications",conferences:"Conferences",awards:"Awards & Honors",reviewer:"Reviewer",references:"References","research-interests":"Research Interests"};
const endpoint={education:"/education/public",experience:"/experience/public",publications:"/research-publications/public",projects:"/projects/public","research-resources":"/research-resources/public","project-wins":"/project-wins/public",supervision:"/supervision/public",certificates:"/certificates/public",conferences:"/conferences/public",awards:"/awards/public",reviewer:"/reviewer/public",references:"/references/public"};
const title=(x,m)=>m==="experience"?x.position:m==="publications"?x.title:m==="education"?x.degree:m==="conferences"?(x.title||x.name):m==="reviewer"?x.journal:x.title||x.name||"Record";
export default function PublicListing(){
 const {module}=useParams();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [search,setSearch]=useState("");
 useEffect(()=>{const load=async()=>{try{if(module==="research-interests"){const r=await api.get("/portfolio");setItems((r.data.data?.researchInterests||[]).map((title,i)=>({_id:String(i),title,description:"Research interest"})));}else{const r=await api.get(endpoint[module]||"");setItems(r.data.data||[]);}}catch(e){setError(e.response?.data?.message||"Unable to load records");}finally{setLoading(false)}};load()},[module]);
 const label=cfg[module]||"Portfolio";const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 return <div className="detail-page"><Link className="back-link" to="/portfolio"><ArrowLeft size={16}/> Portfolio home</Link><div className="detail-hero"><span className="eyebrow">LIVE RECORDS</span><h1>{label}</h1><p>Every visible database record is presented as an individual public item. Select one to open its complete details.</p><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records..." style={{marginTop:25,width:"100%",maxWidth:500,padding:"14px 16px",background:"#111315",border:"1px solid rgba(255,255,255,.1)",borderRadius:10,color:"#fff"}}/></div>{loading?<div>Loading...</div>:error?<div>{error}</div>:<div className="record-grid">{filtered.map(x=><Link className="record-card glass" to={module==="research-interests"?"/portfolio":`/portfolio/${module}/${x._id}`} key={x._id}><small>{x.organization||x.issuer||x.category||x.status||"PUBLIC RECORD"}</small><h3>{title(x,module)}</h3><p>{x.description||x.role||"Open to view complete information."}</p><ArrowUpRight size={16}/></Link>)}</div>}</div>
}
